language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
sudo: required

r_packages:
  - covr

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python python3; fi

apt_packages:
 - python-dev
 - python
 - python3-dev
 - python3

env:
 global:
   - CRAN: http://cran.rstudio.com
 - SNAKECHARMR_PYTHON_VERSION=2
 - SNAKECHARMR_PYTHON_VERSION=3

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library("covr");codecov()'
