language: r

r:
  - release
  - devel

cache: packages

sudo: required

r_packages:
  - covr

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python python3; fi

addons:
  apt:
    packages:
      - python-dev
      - python
      - python3-dev
      - python3

env:
  - SNAKECHARMR_PYTHON_VERSION=2
  - SNAKECHARMR_PYTHON_VERSION=3

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library("covr");codecov()'
