# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

environment:
  USE_RTOOLS: true
  
  matrix:
    - PATH: C:\Python27;%PATH%
      R_ARCH: i386
      GCC_PATH: mingw_32
    
    - PATH: C:\Python27-x64;%PATH%
      R_ARCH: x64
      GCC_PATH: mingw_64
    
    - PATH: C:\Python36;%PATH%
      R_ARCH: i386
      GCC_PATH: mingw_32
    
    - PATH: C:\Python36-x64;%PATH%
      R_ARCH: x64
      GCC_PATH: mingw_64

    - PATH: C:\Rtools\mingw_32\opt\bin;%PATH%
      R_ARCH: i386
      GCC_PATH: mingw_32
      PYTHONHOME: c:\Rtools\mingw_32\opt

    - PATH: C:\Rtools\mingw_64\opt\bin;%PATH%
      R_ARCH: x64
      GCC_PATH: mingw_64
      PYTHONHOME: c:\Rtools\mingw_32\opt

platform: x64
