# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_Py_Initialize <- function() {
    invisible(.Call('SnakeCharmR_rcpp_Py_Initialize', PACKAGE = 'SnakeCharmR'))
}

rcpp_Py_Finalize <- function() {
    invisible(.Call('SnakeCharmR_rcpp_Py_Finalize', PACKAGE = 'SnakeCharmR'))
}

rcpp_Py_run_code <- function(code) {
    .Call('SnakeCharmR_rcpp_Py_run_code', PACKAGE = 'SnakeCharmR', code)
}

rcpp_Py_get_var <- function(varname) {
    .Call('SnakeCharmR_rcpp_Py_get_var', PACKAGE = 'SnakeCharmR', varname)
}

